### PR TITLE
Use named anchor instead of auto-generated section id

### PR DESCRIPTION
**Pull request by kenhys**

### CODE REVIEW

**Comment by kenhys** [comment]
Before:

/on-boarding/proposals/2021-08/kenhys-maintain-debian-packages/#section-9

After:

/on-boarding/proposals/2021-08/kenhys-maintain-debian-packages/#how-to-apply

**Comment by kou** [comment]
This creates `#a-hrefhow-to-applya`...:

```html
<h2 id="a-hrefhow-to-applya"><a href="#how-to-apply">応募方法</a></h2>
```

**Comment by kou** [comment]
This is ugly but works...:

```diff
diff --git a/proposals/2021-08/kenhys-maintain-debian-packages/index.md b/proposals/2021-08/kenhys-maintain-debian-packages/index.md
index d3c9611..7034b20 100644
--- a/proposals/2021-08/kenhys-maintain-debian-packages/index.md
+++ b/proposals/2021-08/kenhys-maintain-debian-packages/index.md
@@ -160,7 +160,7 @@ mentors.debian.netの改善に関しては、まだ[salsa](https://salsa.debian.
 * 2021-07-31(土) 23:59:59 (JST)まで。
 * 2021-08-02(月)に選考・連絡。次週の初回Webミーティング日程調整。
 
-## 応募方法
+## <span id="how-to-apply">応募方法</span>
 
 下記事項を記載の上`on-boarding@oss-gate.org`にメールでご応募ください。
```

**Comment by kenhys** [comment]
In my case, it works.

image

**Comment by kou** [comment]
`href` isn't an anchor that can be referred.
It just refers an anchor.

**Comment by kou** [comment]
We need to use `id` or `name` for anchor that can be referred.

**Comment by kenhys** [comment]
Thanks, I've overlooked it. Fixed now.

**Comment by kou** [comment]
Thanks.

**Pull request merged**
